### PR TITLE
Add files for Ukrainian translation

### PR DESCRIPTION
**Pull request by Hundmann**

### CODE REVIEW

**Comment by purejava** [comment]
Hi,

thanks for the PR.

Please revert commit d634efb2108ba5c3fbb6f7ebba66e30448409753. The directory layout was ok with your first commit, the second commit broke it.

I'll compile the .mo file for you afterwards, add it to your PR, merge it and create a new release, that contains your translations.

That'll take a couple of days, as I do not have a computer at my hands.

Regards,
Ralph

**Comment by purejava** [comment]
That's too much. 🙂
You can now do the following:
`git revert fdd6fcb683cf28ed79264f6c8bd578263d7114b1`

`git revert d634efb2108ba5c3fbb6f7ebba66e30448409753`

That should be it.

**Comment by Hundmann** [comment]
@Hundmann ➜ /workspaces/fedora-update (patch-1) $ git revert fdd6fcb683cf28ed79264f6c8bd578263d7114b1
hint: Waiting for your editor to close the file... 
git revert d634efb2108ba5c3fbb6f7ebba66e30448409753
[patch-1 5f0a4f8] Revert "Delete locale/uk_UA/LC_MESSAGES/update-extension@purejava.org.po"
 1 file changed, 212 insertions(+)
 create mode 100644 locale/uk_UA/LC_MESSAGES/update-extension@purejava.org.po
@Hundmann ➜ /workspaces/fedora-update (patch-1) $ 
@Hundmann ➜ /workspaces/fedora-update (patch-1) $ git revert d634efb2108ba5c3fbb6f7ebba66e30448409753
[patch-1 dee4416] Revert "Rename locale/uk_UA/update-extension@purejava.org.po to locale/uk_UA/LC_MESSAGES/update-extension@purejava.org.po"
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename locale/uk_UA/{LC_MESSAGES => }/update-extension@purejava.org.po (100%)
@Hundmann ➜ /workspaces/fedora-update (patch-1) $

**Comment by Hundmann** [comment]
Thanks for the help, I rolled out the changes :)

**Comment by purejava** [comment]
> Thanks for the help, I rolled out the changes :)

You are welcome. 🙂 Thanks for providing the translation!

This PR is fine now. I'll notify you, when the new version of the plugin containing your translation is live.

**Comment by Hundmann** [comment]
Thank you very much☺️


сб, 11 трав. 2024 р. о 19:19 Ralph Plawetzki ***@***.***>
пише:

**Comment by Hundmann** [comment]
Awesome, thanks!

пт, 17 трав. 2024 р. о 20:32 Ralph Plawetzki ***@***.***>
пише:

**Comment by purejava** [comment]
> This PR is fine now. I'll notify you, when the new version of the plugin containing your translation is live.

Your translations are live. Version 13 of the extension was published. It contains your work.

**Comment by Hundmann** [comment]
Awesome, thanks for the update!

пт, 17 трав. 2024 р. о 20:56 Ralph Plawetzki ***@***.***>
пише:

**Pull request merged**
